Story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tugas.urls')),
]

tugas/urls.py
from django.urls import path
from . import views



app_name = 'tugas'

urlpatterns = [
path('',views.status,name='status'),
path('confirmation/', views.confirmation, name='confirmation')



]

tugas/models.py
from django.db import models

# Create your models here

class Status(models.Model):
    name = models.TextField('name', max_length=30)
    status = models.TextField('status', max_length = 100)

    def __str__(self):
        return self.status

tugas/forms.py
from django import forms
from .models import Status
##Create your forms here

class StatusForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : "buat nama",
        'type' : 'text',
        'maxlength' : '30',
        'required' : True,
        'label' : '',
    }))

    status = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : "buat status",
        'type' : 'text',
        'maxlength' : '100',
        'required' : True,
        'label' : '',
    }))

    

tugas/views.py
from .models import Status
from .forms import StatusForm
from django.shortcuts import render,redirect


# Create your views here.

def confirmation(request):
	if (request.method == 'POST'):
		form = StatusForm(request.POST)
		if (form.is_valid()):
			name = form.cleaned_data['name']
			status = form.cleaned_data['status']
			newstatus = Status.objects.create(name=name, status = status)
			newstatus.save()
			return redirect('tugas:status')
	else:
		form = StatusForm()
	return render(request,'pages/confirmation.html')

def status(request):
	stats = Status.objects.all()
	if (request.method == 'POST'):
		form = StatusForm(request.POST)
		if (form.is_valid()):
			username= form.cleaned_data['name']
			userstatus= form.cleaned_data['status']
			response = {'name':username, 'status':userstatus}
			return render(request, 'pages/confirmation.html',response)
	else:
		form = StatusForm()
	return render(request, 'pages/index.html', {'stats': stats, 'form':form})

tugas/templates/pages/base.html
{% load static %}
<!DOCTYPE html>


<html lang="en" dir="ltr">


<head>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">
  <link rel="stylesheet" href="{% static "css/main.css" %}">
  <link href="https://fonts.googleapis.com/css?family=Bebas+Neue&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600,700,800&display=swap" rel="stylesheet">

</head>

<body>
  {% block content %}
  {% endblock %}
  <script src="/static/js/bootstrap.min.js"></script>
</body>

</html>

tugas/templates/pages/confirmation.html
{% extends 'pages/base.html' %}
{% load static %}
{% block content %}

<div class="container ml-5 mt-5 mr-5">
  <h1>Are you sure?</h1>
  <form method="POST" action="{% url 'tugas:confirmation' %}">
    {% csrf_token %}
    <ul>
      <li>Name: <input type="text" class="form-control" id="name" name="name" maxlength="30" readonly value="{{ name }}"> </li>
      <li>Status: <input type="text" class="form-control" id="status" name="status" maxlength="100" readonly value="{{ status }}"> </li>
    </ul>
    <input type="submit" value="Submit" name="submitt">
    <a href="{% url 'tugas:status' %}"><input type="button" value="Cancel" name="cancell"></input></a>
  </form>
</div>


{% endblock %}

tugas/templates/pages/index.html
{% extends 'pages/base.html' %}
{% load static %}


{% block content %}

<body>


  <div class="container ml-5 mt-5 mr-5">
    <h1>Hello, how are you?</h1>
    <form method="POST">
      {% csrf_token %}
      <label style="font-size:20px; font-weight: 600">Name</label>
      <input type="text" class="form-control" name="name" maxlength="30" placeholder="Your Name" required> <br>
      <label style="font-size:20px; font-weight: 600">Status</label>
      <input type="text" class="form-control" name="status" maxlength="100" placeholder="Your Status" required>
      <input type="submit" value="Submit" name="submitstatus">
      <!-- <a class="btn btn-primary" href="{% url 'tugas:confirmation' %}">Redirect </a> -->
    </form>
  </div>

  <h1 class="text-center mt-5 mb-5" style="font-weight:700">Status</h1>
  <div class=" col-lg-12 col-md-12 col-sm-12">
    <div class="row">
      <table class="table">
        <thead style="font-size: 25px">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody style="font-size: 20px">
          {% for stats in stats %}
          <tr>
            <td>{{stats.name}}</td>
            <td>{{ stats.status }}</td>
          </tr>
          {% endfor %}

        </tbody>
      </table>
    </div>
  </div>
</body>
{% endblock %}